### ISSUE TITLE
Rails App Checklist

### ISSUE THREAD

**Issue by Johnsalzarulo** [withbetterco/guidebook#1]
Once done - Let's extract the overall tooling and steps created in last week's "tooling" updates into a single checklist / source of truth. I have a few new projects starting up and I want to be sure all the tooling is properly configured. 

High Level: 

- [x] Linting / Style guide
- [x] CI Testing 
- [x] Deployment (How to configure Semaphore) 
- [x] Error + Performance Monitoring 
- [ ] .env
- [ ] Database Backups

**Comment by Johnsalzarulo** [comment]
Info on scheduling backups: 
https://devcenter.heroku.com/articles/heroku-postgres-backups#scheduling-backups

**Comment by Johnsalzarulo** [comment]
**Development / Deployment Process:** 

**Development:** 
- Github issue Opened 
- Github Issue assigned to a developer 
- New branch from master pulled to address issue
- Work is done on this branch 
- Hours are tracked referencing the client and issue name 
- in progress the a PR is opened with a [WIP] 
- When test coverage is passing and issue specifications have been resolved it is assigned for review
- Review happens- if changes are needed they are noted and it's reassigned to the pull request author
- Once review is approved and the CI has all tests passing it is merged with master or beta 

**Beta Deployment**
- All major feature revisions touching a core model or a larger refactor need QA testing on the staging server - the staging server should only use test fixture data and should mimic production as closely as possible. 
- From Semaphore "Manually Deploy" the branch of code you'd like to test - this "manual" deploy will run the scripts and deploy that branch to the beta server. 
- Do the manual QA testing needed. 
- If all is good you can then merge that branch to master for Production Deployment 

**Production Deployment**

- PR is merged to master
- Semaphore watches for changes on master branch
- When an update is detected Semaphore runs all the tests and scripts on the master branch
- Then - Semaphore actually deploys the code to production. 
- The semaphore script should run any deployments, migrations or other utilities needed for a deploy
- Because of this flow a master merge should never happen durring peak site hours
- A semaphore deploy and script could cause downtime in production.

**Comment by Johnsalzarulo** [comment]
Error Monitoring 

Although error monitoring is important keep in mind it can be a bit noisy at times. For example - sloppy bots crawling the web may be sending random GET requests to an invalid endpoint. Or web-crawlers try to visit a page that doesn't exist. The goal is to have the system handle some of these anomalies without actually throwing an error, however - sometimes these may be unforeseen. 

That said - it's important to keep an eye on error monitoring especially when there has been a recent large deploy - just to make sure everything goes smoothly in production. 

In general we want to aim for less than 1% of sessions experiencing any kind of server error or issue. Anything over that would be considered an addressable issue. 

More than 10% is considered an urgent and should work to be addressed within 24 business hours if possible. 

More than 25% of sessions with an error should be considered an "emergency" within reason. (A bug in our work isn't literally going to kill anyone, however - it could be costing a lot of money or trust) - Essentially - we shouldn't work on anything else until it's addressed and we need to be updating clients constantly about the scope of the situation and how it's being solved.

**Comment by Johnsalzarulo** [comment]
Fixing an Error: 

Step 1: 
Know the impact - dig through the AppSignal logs, analytics or any other data at your disposal. 

Step 2: 
Open up an issue - take the time to accurately document the scope and impact of the bug. This is a good time to communicate it to the client as well. 

Step 3: 
Open a branch to address the issue and follow the same development workflow that is usually followed. 

Step 4: 
On this branch write a test that replicates the issue - you should have a test that is failing that represents the desired success state. This often means you need to create some more test data and really think through the setup to be sure you are replicating the issue. 

Step 5: 
Get the tests green - Once you've tracked down and fixed the bug the failing tests should be green.

**Comment by Johnsalzarulo** [comment]
Hmmmm. This is expanding out of the scope of the rails checklist. All this is good to document but maybe it should go elsewhere in the "guide"

**Comment by PolarisTLX** [comment]
This is all great stuff!  I can see about working it into organised sections incorporated into the Guidebook. 
We can then take a step back and see if there are sections that should separated into their own file with a link "see this other document for more info on this topic".

**Comment by Johnsalzarulo** [comment]
Maybe a document labeled something like "tooling & setup" that walks the the basic preferred libraries, vendors and configuration. 

Then a document called something like "Rails Development Deployment and Management" that has the Git work flow - error tracking and error resolution?

**Comment by PolarisTLX** [comment]
Alright I believe a lot of the content is now there.

- The section on backups still needs to be written.
- The section on Error + Performance Monitoring (AppSignal) has been written but I am not sure if it's how you want it. Let me know.
- The .env task could just be a small section.  A little blurb is written about it in other parts of the guidebook.
